version: '3'

services:
  api:
    image: hackathonluzern22/partyparty:latest
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGHOST: database
      PGPASSWD: postgres
      PGDATABASE: partyparty
      PGPORT: 5432
      NODE_ENV: production
      PORT: 3000
    ports:
      - "4004:3000"

  database:
    image: 'postgres:latest'
    restart: "always"
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=partyparty
    volumes:
      - pgdb-data:/var/lib/postgresql/data/
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pg-net

  admin:
    image: 'dpage/pgadmin4'
    restart: "always"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    #ports:
    #  - "5480:80"
    networks:
      - pg-net

networks:
  pg-net:

volumes:
  pgadmin4-data:
  pgdb-data:
